name: Compile check LaTeX
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Find modified LaTeX files
        id: find
        run: |
          git remote set-branches --add origin main
          git fetch
          changed_files=$(git diff --name-only origin/main | grep 'main.tex$') || true
          if [ $(echo "$changed_files" | wc -l) -gt 1 ]; then
            echo "::error::You are supposed to modify one document per branch"
            exit 1
          elif [ -n $changed_files ]; then 
            echo "No document was modified"
          fi
          echo "file=$changed_files" >> $GITHUB_OUTPUT
      - name : Install dependencies
        run: |
          if [ -n "${{ steps.find.outputs.file }}" ]; then
            sudo apt install -y texlive texlive-latex-extra texlive-lang-italian
          fi
      - name: Compile the modified LaTeX file
        run: |
          if [ -n "${{ steps.find.outputs.file }}" ]; then
            directory=$(dirname "${{ steps.find.outputs.file }}")
            file=$(basename "${{ steps.find.outputs.file }}")
            cd "$directory"
            pdflatex "$file"        
          fi